BENCHMARK="MOT17"
# TRACKERS_TO_EVAL="quantyolov8_4w4a_mot15_cl0"
TRACKERS_TO_EVAL="fasttracker_mot17_pub"
TRACKERS_FOLDER=${PWD}/dcf_mot/output
# SINGLE_SEQUENCE="ETH-Sunnyday"
SINGLE_SEQUENCE="None"
cd TrackEval
python scripts/run_mot_challenge.py --SINGLE_SEQUENCE ${SINGLE_SEQUENCE} --SKIP_SPLIT_FOL False --METRICS CLEAR --BENCHMARK ${BENCHMARK} --TRACKERS_FOLDER ${TRACKERS_FOLDER} --TRACKERS_TO_EVAL "${TRACKERS_TO_EVAL}"