# SPLIT_TO_EVAL="train"
SPLIT_TO_EVAL="val_half"

BENCHMARK="MOT17"

# TRACKERS_TO_EVAL="quantyolov8_4w4a_mot15_cl0"
TRACKERS_TO_EVAL="yolox_mot17_val_half_bytetracker2"

TRACKERS_FOLDER=${PWD}/dcf_mot/output
# TRACKERS_FOLDER=${PWD}/dcf_mot/output/params_search_bytetracker2_dcf_searchfurther_apce

# SINGLE_SEQUENCE="ETH-Sunnyday"
SINGLE_SEQUENCE="None"

METRICS="HOTA"

cd TrackEval
python scripts/run_mot_challenge.py --SPLIT_TO_EVAL ${SPLIT_TO_EVAL} --SINGLE_SEQUENCE ${SINGLE_SEQUENCE} --SKIP_SPLIT_FOL False --METRICS ${METRICS} --BENCHMARK ${BENCHMARK} --TRACKERS_FOLDER ${TRACKERS_FOLDER} --TRACKERS_TO_EVAL "${TRACKERS_TO_EVAL}"
# python scripts/run_mot_challenge.py --SPLIT_TO_EVAL ${SPLIT_TO_EVAL} --SINGLE_SEQUENCE ${SINGLE_SEQUENCE} --SKIP_SPLIT_FOL False --METRICS ${METRICS} --BENCHMARK ${BENCHMARK} --TRACKERS_FOLDER ${TRACKERS_FOLDER}